version: '3'
services:
  front:
    container_name: sokuadd-front
    build: ./front
    ports:
    - 3000:3000
    volumes:
    - ./front/src:/app
    stdin_open: true
    tty: true
    links:
    - back:back

  back:
    container_name: sokuadd-back
    build: ./back
    volumes:
    - ./back/src:/var/www/html
    - ./data/mysqld:/var/run/mysqld
    depends_on:
    - mysql
    ports:
    - 9000:9000
    
  nginx:
    image: nginx:1.18.0
    container_name: sokuadd-nginx
    ports:
    - 80:80
    volumes:
    - ./back/src:/var/www/html
    - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - front
    - back
    links:
    - front:front
    - back:back
    
  mysql:
    image: mysql:8.0.20
    container_name: sokuadd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sokuadd
      MYSQL_DATABASE: sokuadd-local_db
      MYSQL_USER: sokuadd
      MYSQL_PASSWORD: sokuadd
      TZ: 'Asia/Tokyo'
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
    
    volumes:
    - ./data/data:/var/lib/mysql
    - ./data/sokuadd.cnf:/etc/mysql/conf.d/sokuadd.cnf
    - ./data/sokuadd-query.log:/var/log/mysql/sokuadd-query.log

    ports:
    - 3306:3306